export const CHANGE_CURRENT_MODULE_TYPE = 'CHANGE_CURRENT_MODULE_TYPE'
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'

export const SET_CURRENT_BOOK_TAGS = 'SET_CURRENT_BOOK_TAGS'
export const SET_CURRENT_BOOK_TAG = 'SET_CURRENT_BOOK_TAG'
export const SET_TAG_BOOKS = 'SET_TAG_BOOKS'
export const SET_CURRENT_TAG_BOOKS = 'SET_CURRENT_TAG_BOOKS'
export const SET_CURRENT_BOOK_TYPE = 'SET_CURRENT_BOOK_TYPE'
export const SET_TYPE_BOOKS = 'SET_TYPE_BOOKS'
export const SET_CURRENT_TYPE_BOOKS = 'SET_CURRENT_TYPE_BOOKS'

export const SET_CURRENT_MOVIE_TIME_TYPE = 'SET_CURRENT_MOVIE_TIME_TYPE'
export const SET_TIME_TYPE_MOVIES = 'SET_TIME_TYPE_MOVIES'
export const SET_CURRENT_TIME_TYPE_MOVIES = 'SET_CURRENT_TIME_TYPE_MOVIES'
export const SET_CURRENT_MOVIE_TAG = 'SET_CURRENT_MOVIE_TAG'
export const SET_TAG_MOVIES = 'SET_TAG_MOVIES'
export const SET_CURRENT_TAG_MOVIES = 'SET_CURRENT_TAG_MOVIES'

export const SET_CURRENT_MUSIC_TAG = 'SET_CURRENT_MUSIC_TAG'
export const SET_TAG_MUSICS = 'SET_TAG_MUSICS'
export const SET_CURRENT_TAG_MUSICS = 'SET_CURRENT_TAG_MUSICS'

export const SET_CITIES = 'SET_CITIES'
export const SET_CURRENT_CITY = 'SET_CURRENT_CITY'
